LocadoraES/Controllers/AutenticacaoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LocadoraES.Models;
using LocadoraES.ViewModel;
using LocadoraES.Utilidades;
using System.Security.Claims;

namespace LocadoraES.Controllers
{
    public class AutenticacaoController : Controller
    {
        private UsersContext db = new UsersContext();

        // GET: Autenticacao
        public ActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Cadastrar(CadastroUsersViewModel cviewmodel)
        {   //verifica se os dados são valido, caso contrario retorna para view
            if (!ModelState.IsValid)
            {
                return View(cviewmodel);
            }
            //verificar se ja existe usuario cadastrado com mesmo login
            if (db.Users.Count(u => u.Login == cviewmodel.Login) > 0)
            {
                ModelState.AddModelError("Login", "Já existe usuário com este Login");
                return View(cviewmodel);
            }
            User newUser = new User
            {
                Nome = cviewmodel.Nome,
                Login = cviewmodel.Login,
                Senha = Hash.GenerateHash(cviewmodel.Senha)
              //Senha = cviewmodel.Senha
            };

            db.Users.Add(newUser);
            db.SaveChanges();

            //mensagem de cadastro
            TempData["Mensagem"] = "Cadastro realizado com sucesso. Preceda o login.";
            return RedirectToAction("Login");
        }

        public ActionResult Login(string ReturnUrl)
        {
            var lviewmodel = new LoginViewModel
            {
                UrlRetorno = ReturnUrl
            };

            return View(lviewmodel);
        }

        [HttpPost]
        public ActionResult Login(LoginViewModel lviewmodel)
        {
            //verificar erro de validação
            if (!ModelState.IsValid)
            {
                return View(lviewmodel);
            }

            //localizar usuario no DB
            var user = db.Users.FirstOrDefault(u => u.Login == lviewmodel.Login);
            //verificando dados login
            if (user == null)
            {
                ModelState.AddModelError("Login", "Login incorreto");
                return View(lviewmodel);
            }
             if (user.Senha != Hash.GenerateHash(lviewmodel.Senha)) // ajustar qndo arrumar criptografia
            
            {
                ModelState.AddModelError("Senha", "Senha incorreta");
                return View(lviewmodel);
            }

            //define identidade do usuario
            var identity = new ClaimsIdentity(new[]
            {
                new Claim(ClaimTypes.Name, user.Nome),
                new Claim("Login", user.Login)
            }, "ApplicationCookie");

            Request.GetOwinContext().Authentication.SignIn(identity);

            //redirecionamento do usuario logado
            if (!String.IsNullOrWhiteSpace(lviewmodel.UrlRetorno) || Url.IsLocalUrl(lviewmodel.UrlRetorno))
                return Redirect(lviewmodel.UrlRetorno);
            else
                return RedirectToAction("Index", "Filme");
        }

        public ActionResult Logout()
        {
            Request.GetOwinContext().Authentication.SignOut("ApplicationCookie");
            return RedirectToAction("Index", "Home");
        }

    }
}

LocadoraES/Controllers/FilmeController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LocadoraES.Models;
using Dapper;

namespace LocadoraES.Controllers
{
    public class FilmeController : Controller
    {
        private LocadoraContext db = new LocadoraContext();

        
        // GET: Filme
        [Authorize]
        public ActionResult Index()
        {
           return View(db.Filmes.ToList());
           
        }

        [Authorize]
        public ActionResult CadastroFilme()
        {
            //carrega o id do genero para o dropdown
            ViewBag.IdGenero = new SelectList(db.Generos.ToList(),
           "Id", "Nome");
            return View(new Filme());
        }

        
        [HttpPost]
        public ActionResult CadastroFilme(Filme filme)
        {

            if (!ModelState.IsValid)
            {
                ViewBag.IdGenero = new SelectList(db.Generos.ToList(),
           "Id", "Nome");
                
                return View("CadastroFilme", filme);

            }

            if (filme.Nome == null || filme.Nome == "")
            {
                ModelState.AddModelError("Nome", "Informar o Nome");
                return View("CadastroFilme");
            }

            if (filme.IdGenero == 0)
            {
                ModelState.AddModelError("IdGenero", "Informar o Gênero");
                return View("CadastroFilme");
            }


            //retorna o Id do genero
            ViewBag.IdGenero = new SelectList(
            new Filme().ListaGenero(), "Id", "Nome", filme.IdGenero);
            db.Filmes.Add(filme);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [Authorize]
        public ActionResult AlterarFilme(int? Id)
        {
            if (Id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Filme filme = db.Filmes.Find(Id);
            if (filme == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdGenero = new SelectList(db.Generos.ToList(),
          "Id", "Nome");
            return View(filme);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AlterarFilme([Bind(Include = "Id, Nome, DhCriacao, FlAtivo, IdGenero")] Filme filme)
        {
            if (ModelState.IsValid)
            {
                ViewBag.IdGenero = new SelectList(
               new Filme().ListaGenero(), "Id", "Nome", filme.IdGenero);
                db.Entry(filme).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(filme);
        }


        public ActionResult ApagarFilme(int[] Id)
        {
            if (Id == null)
            {
                ModelState.AddModelError("", "Nenhum item foi selecionado para deletar");
            }

            foreach (int item in Id)
            {
                Filme filme = db.Filmes.Find(item);
                db.Filmes.Remove(filme);
                db.SaveChanges();
            }

            return View("Index", db.Filmes.ToList());

        }

    }
}

LocadoraES/Controllers/GeneroController.cs
using LocadoraES.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Dapper;
using System.Data.SqlClient;
using System.Configuration;

namespace LocadoraES.Controllers
{
    public class GeneroController : Controller
    {
        private LocadoraContext db = new LocadoraContext();
        
     

        // GET: Genero
        [Authorize]
        public ActionResult Index()
        {
            List<Genero> generos = new List<Genero>();
            using (IDbConnection db = new SqlConnection(ConfigurationManager.ConnectionStrings["Locadora"].ConnectionString))
            {

                generos = db.Query<Genero>("Select * From Generos").ToList();
            }
            // return View(db.Generos.ToList());
            return View(generos);
        }



        [Authorize]
        public ActionResult CadastroGenero()
        {
            return View(new Genero());
        }

        [HttpPost]
        public ActionResult CadastroGenero(Genero genero)
        {
            if (!ModelState.IsValid)
            {
                return View("CadastroGenero", genero);
            }

            if (genero.Nome == null || genero.Nome == "")
            {
                ModelState.AddModelError("Nome", "Informar o Gênero");
                return View("CadastroGenero");
            }

            db.Generos.Add(genero);
            db.SaveChanges();

            return RedirectToAction("Index");
        }



        public ActionResult ApagarGenero(int[] Id)
        {
            if (Id == null)
            {
                ModelState.AddModelError("", "Nenhum item foi selecionado para deletar");
            }



            foreach (int item in Id)
            {
                Genero genero = db.Generos.Find(item);
                db.Generos.Remove(genero);
                db.SaveChanges();
            }

            return View("Index", db.Generos.ToList());

        }
    }
}

LocadoraES/Controllers/LocacaoController.cs
using LocadoraES.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Dapper;
using System.Net;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Data;

namespace LocadoraES.Controllers
{
    public class LocacaoController : Controller
    {
     
        private LocadoraContext db = new LocadoraContext();

        // GET: Locacao
        [Authorize]
        public ActionResult Index()
        {
            return View(db.Locacoes.ToList());
        }


        [Authorize]
        public ActionResult CadastroLocacao()
        {
            ViewBag.Filmes = db.Filmes;
            return View(new Locacao());
        }

        
        [HttpPost]
        public ActionResult CadastroLocacao(int[] FilmeIds, Locacao locacao)
        {

            if (!ModelState.IsValid)
            {
                return View("CadastroLocacao");

            }

            if(locacao.CPF == null || locacao.CPF == "")
            {
                ModelState.AddModelError("CPF", "Informar o CPF");
                return View("CadastroLocacao");
            }


            locacao.Filmes = new List<Filme>();
            foreach (int filmeId in FilmeIds)
            {
                Filme filme = db.Filmes.Find(filmeId);
                locacao.Filmes.Add(filme);
            }
            db.Locacoes.Add(locacao);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [Authorize]
        public ActionResult AlterarLocacao(int? Id)
        {
            if (Id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Locacao locacao = db.Locacoes.Find(Id);
            if (locacao == null)
            {
                return HttpNotFound();
            }
            ViewBag.Filmes = locacao.Filmes;
            
                return View(locacao);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AlterarLocacao(Locacao locacao, int[] FilmeIds)
        {
            if (ModelState.IsValid)
            {
                db.Entry(locacao).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(locacao);
        }


        public ActionResult ApagarLocacao(int[] Id)
        {
            if (Id == null)
            {
                ModelState.AddModelError("", "Nenhum item foi selecionado para deletar");
            }

            foreach (int item in Id)
            {
                Locacao locacao = db.Locacoes.Find(item);
                db.Locacoes.Remove(locacao);
                db.SaveChanges();
            }

            return View("Index", db.Locacoes.ToList());

        }

    }

}

LocadoraES/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title Locadora </title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <container>
        <div class="navbar navbar-inverse navbar-fixed-top navbar-dark" >
            <div class="container-fluid" style="margin: 11px">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <ul class="nav navbar-nav navbar-right">
                        @if (User.Identity.IsAuthenticated)
                        {
                            @Html.ActionLink("Filmes", "Index", "Filme", new { area = "" }, new { @class = "navbar-brand" })
                            @Html.ActionLink("Gêneros", "Index", "Genero", new { area = "" }, new { @class = "navbar-brand" })
                            @Html.ActionLink("Locação", "Index", "Locacao", new { area = "" }, new { @class = "navbar-brand" })
                        }
                    </ul>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-right">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">@User.Identity.Name<span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li>@Html.ActionLink("Alterar senha", "AlterarSenha", "PerfilManage")</li>
                                    <li>@Html.ActionLink("Sair", "Logout", "Autenticacao")</li>

                                </ul>
                            </li>
                        }
                        else
                        {
                            <li>@Html.ActionLink("Login", "Login", "Autenticacao", new { area = "" }, new { @class = "navbar-brand" })</li>
                            <li>@Html.ActionLink("Cadastre-se", "Cadastrar", "Autenticacao", new { area = "" }, new { @class = "navbar-brand" })</li>
                        }

                    </ul>
                </div>
            </div>
        </div>
    </container>
    <div class="container body-content">
        @RenderBody()
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    @RenderSection("scripts", false)
</body>
</html>