LocadoraES/Models/Filme.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace LocadoraES.Models
{
    [Table("Filmes")]
    public class Filme
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Preencha o nome")]
        [MaxLength(100)]
        public string Nome { get; set; }

        [Display(Name = "Data de criação")]
        public DateTime DhCriacao { get; set; }

        [Display(Name = "Ativo")]
        public bool FlAtivo { get; set; }


        [Required(ErrorMessage = "Escolha/Cadastre um gênero")]
        [ForeignKey("Genero")]
        public int IdGenero { get; set; }

        [Required(ErrorMessage = "Escolha/Cadastre um gênero")]
        public int IdLocacao { get; set; }

        public virtual ICollection<Locacao> Locacoes { get; set; }

        public virtual Genero Genero { get; set; }

        
        public virtual List<Genero> ListaGenero()
        { return new List<Genero>(); }

       

    }


}

LocadoraES/Controllers/FilmeController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LocadoraES.Models;
using Dapper;

namespace LocadoraES.Controllers
{
    public class FilmeController : Controller
    {
        private LocadoraContext db = new LocadoraContext();

        
        // GET: Filme
        [Authorize]
        public ActionResult Index()
        {
           return View(db.Filmes.ToList());
           
        }

        [Authorize]
        public ActionResult CadastroFilme()
        {
            //carrega o id do genero para o dropdown
            ViewBag.IdGenero = new SelectList(db.Generos.ToList(),
           "Id", "Nome");
            return View(new Filme());
        }

        
        [HttpPost]
        public ActionResult CadastroFilme(Filme filme)
        {

            if (!ModelState.IsValid)
            {
                ViewBag.IdGenero = new SelectList(db.Generos.ToList(),
           "Id", "Nome");
                
                return View("CadastroFilme", filme);

            }

            if (filme.Nome == null || filme.Nome == "")
            {
                ModelState.AddModelError("Nome", "Informar o Nome");
                return View("CadastroFilme");
            }

            if (filme.IdGenero == 0)
            {
                ModelState.AddModelError("IdGenero", "Informar o Gênero");
                return View("CadastroFilme");
            }


            //retorna o Id do genero
            ViewBag.IdGenero = new SelectList(
            new Filme().ListaGenero(), "Id", "Nome", filme.IdGenero);
            db.Filmes.Add(filme);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [Authorize]
        public ActionResult AlterarFilme(int? Id)
        {
            if (Id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Filme filme = db.Filmes.Find(Id);
            if (filme == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdGenero = new SelectList(db.Generos.ToList(),
          "Id", "Nome");
            return View(filme);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AlterarFilme([Bind(Include = "Id, Nome, DhCriacao, FlAtivo, IdGenero")] Filme filme)
        {
            if (ModelState.IsValid)
            {
                ViewBag.IdGenero = new SelectList(
               new Filme().ListaGenero(), "Id", "Nome", filme.IdGenero);
                db.Entry(filme).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(filme);
        }


        public ActionResult ApagarFilme(int[] Id)
        {
            if (Id == null)
            {
                ModelState.AddModelError("", "Nenhum item foi selecionado para deletar");
            }

            foreach (int item in Id)
            {
                Filme filme = db.Filmes.Find(item);
                db.Filmes.Remove(filme);
                db.SaveChanges();
            }

            return View("Index", db.Filmes.ToList());

        }

    }
}

LocadoraES/Controllers/GeneroController.cs
using LocadoraES.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Dapper;
using System.Data.SqlClient;
using System.Configuration;

namespace LocadoraES.Controllers
{
    public class GeneroController : Controller
    {
        private LocadoraContext db = new LocadoraContext();
        
     

        // GET: Genero
        [Authorize]
        public ActionResult Index()
        {
            List<Genero> generos = new List<Genero>();
            using (IDbConnection db = new SqlConnection(ConfigurationManager.ConnectionStrings["Locadora"].ConnectionString))
            {

                generos = db.Query<Genero>("Select * From Generos").ToList();
            }
            // return View(db.Generos.ToList());
            return View(generos);
        }



        [Authorize]
        public ActionResult CadastroGenero()
        {
            return View(new Genero());
        }

        [HttpPost]
        public ActionResult CadastroGenero(Genero genero)
        {
            if (!ModelState.IsValid)
            {
                return View("CadastroGenero", genero);
            }

            if (genero.Nome == null || genero.Nome == "")
            {
                ModelState.AddModelError("Nome", "Informar o Gênero");
                return View("CadastroGenero");
            }

            db.Generos.Add(genero);
            db.SaveChanges();

            return RedirectToAction("Index");
        }



        public ActionResult ApagarGenero(int[] Id)
        {
            if (Id == null)
            {
                ModelState.AddModelError("", "Nenhum item foi selecionado para deletar");
            }



            foreach (int item in Id)
            {
                Genero genero = db.Generos.Find(item);
                db.Generos.Remove(genero);
                db.SaveChanges();
            }

            return View("Index", db.Generos.ToList());

        }
    }
}

LocadoraES/Views/Filme/AlterarFilme.cshtml
@model LocadoraES.Models.Filme
@{
    ViewBag.Title = "AlterarFilme";
}

@using (Html.BeginForm("AlterarFilme", "Filme"))
{
    @Html.AntiForgeryToken()
    <br />
    <br />
    <br />
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h4>Preencha os dados dos filmes</h4>
        </div>
        <div class="panel-body">
            <div hidden>
                @Html.LabelFor(model => model.Id)
                @Html.TextBoxFor(model => model.Id)
            </div>
            <div class="row">
                <div class="form-group col-md-12">
                    @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control", placeholder = "Nome do filme" } })
                    @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="row">
                <div class="form-group col-md-12">
                    <label for="DhCriacao">Data de criação</label>
                    @if (Model.DhCriacao.Year < 1500)
                    {
                        <input type="date" value=@DateTime.Now.ToString("yyyy-MM-dd") name="dhCriacao" class="form-control" />
                    }
                    else
                    {
                        <input type="date" value=@Model.DhCriacao.ToString("yyyy-MM-dd") name="dhCriacao" class="form-control" />
                    }
                </div>
            </div>

            <div class="row">
                <div class="form-group col-md-12" style="align-content:center">
                    @Html.LabelFor(model => model.FlAtivo)
                    @Html.CheckBoxFor(model => model.FlAtivo, new { @class = "checkbox" })
                </div>
            </div>

            <div>
                @Html.LabelFor(model => model.IdGenero)
                @Html.DropDownList("IdGenero")
                @Html.ValidationMessageFor(model => model.IdGenero)
            </div>
        </div>
        <div class="panel-footer">
            <input type="submit" value="Alterar" class="btn btn-primary">
        </div>
    </div>



}


@section scripts {
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
}

LocadoraES/Views/Filme/CadastroFilme.cshtml
@model LocadoraES.Models.Filme
@{
    ViewBag.Title = "CadastroFilme";
}

@using (Html.BeginForm("CadastroFilme", "Filme"))
{
    <br />
    <br />
    <br />
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h4>Preencha os dados do filme</h4>
        </div>
        <div class="panel-body">
            <div hidden>
                @Html.LabelFor(model => model.Id)
                @Html.TextBoxFor(model => model.Id)
            </div>
            <div class="row">
                <div class="form-group col-md-12">
                    @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control", placeholder = "Nome do filme" } })
                    @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="row">
                <div class="form-group col-md-12">
                    <label for="DhCriacao">Data de criação</label>
                    @if (Model.DhCriacao.Year < 1500)
                    {
                        <input type="date" value=@DateTime.Now.ToString("yyyy-MM-dd") name="dhCriacao" class="form-control" />
                    }
                    else
                    {
                        <input type="date" value=@Model.DhCriacao.ToString("yyyy-MM-dd") name="dhCriacao" class="form-control" />
                    }
                </div>
            </div>

            <div class="row">
                <div class="form-group col-md-12" style="align-content:center">
                    @Html.LabelFor(model => model.FlAtivo)
                    @Html.CheckBoxFor(model => model.FlAtivo, new { @class = "checkbox" })
                </div>
            </div>

            <div>
                @Html.Label("Gênero")
                @Html.DropDownList("IdGenero", String.Empty)
                @Html.ValidationMessageFor(model => model.IdGenero, "", new { @class = "text-danger" })

                @Html.ActionLink("Cadastrar Gênero", "CadastroGenero", "Genero", new { area = "" }, new { @class = "btn btn-secondary btn-sm" })
            </div>

        </div>
        <div class="panel-footer">
            <input type="submit" value="Cadastrar" class="btn btn-success">
            <input type="submit" value="Voltar" class="btn btn-secondary" onClick=" javascript : history.back(-1);">
        </div>

    </div>

}


@section scripts {
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
}

LocadoraES/Views/Filme/Index.cshtml
@model IEnumerable<LocadoraES.Models.Filme>


@{
    ViewBag.Title = "Filmes";
}


@if (TempData["Mensagem"] != null)
{
    <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">x</button>
        @TempData["Mensagem"]
    </div>
}

@using (Html.BeginForm("ApagarFilme", "Filme", FormMethod.Get))
{
    <br />
    <br />
    <br />
    <div class="container">
        <h2>Lista de filmes</h2>
        @Html.ValidationSummary(true)
        <table class="table">
            <tbody>
                <tr>
                <tr>
                    <th>
                        <label>Nome</label>
                    </th>
                    <th>
                        <label>Data de criação</label>
                    </th>
                    <th>
                        <label>Ativo</label>
                    </th>
                    <th>
                        <label>Genero</label>
                    </th>
                    <th>
                        <label>Alterar</label>
                    </th>
                    <th>
                        <label>Excluir</label>
                    </th>
                </tr>
                @if (Model != null)
                {
                    foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                <label for="@item.Nome.">@item.Nome </label>
                            </td>
                            <td>
                                <label for="@item.DhCriacao">@item.DhCriacao.ToString("dd-MM-yyyy") </label>
                            </td>
                            <td>
                                @if (item.FlAtivo == true)
                                {
                                    <label> Sim </label>}
                                else
                                {
                                    <label> Não </label>}
                            </td>
                            <td>
                                <label for="@item.Genero.Nome"> @item.Genero.Nome</label>
                            </td>
                            <td>
                                @Html.ActionLink("Alterar", "AlterarFilme", "Filme", new { @Id = item.Id }, null)
                            </td>
                            <td>
                                <input type="checkbox"
                                       name="Id"
                                       value="@item.Id" id="@item.Id" />
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
        @Html.ActionLink("Cadastrar Filme", "CadastroFilme", "Movie", new { @class = "btn btn-default" })
        <input type="submit" value="Excluir" class="btn btn-default" />
    </div>
}

@section scripts {
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
}